spring.application.name=ms-usuarios

server.port=8070

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=topdeck
spring.datasource.password=topdeck
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
